### ISSUE TITLE
Question about the KBQA task

### ISSUE THREAD

**Issue by chuckhope** [sinovation/ZEN2#2]
Dear authors,

I have seen the ZEN2 achieves great success on the NLPCC-DBQA task from ERNIE 3 paper, I have gone through GitHub but found no answer yet for the DBQA task except the using NLPCC-DBQA dataset to do sequence-level classification fine-tune.  I wonder can you give me some hint on how you apply ZEN2 to the DBQA task i.e. semantic parsing or information retrieving (embedding)? Thanks a lot. 

Best Regards,
Zhang Yong

**Comment by yuanheTian** [comment]
Hi Zhang,

Thanks for being interested in ZEN2 and thanks for your great question.

In our paper, we tested our model (i.e., ZEN2) on the NLPCC-DBQA dataset following the sequence-level classification paradigm; at present, we do not test our model on other DBQA tasks (e.g., semantic parsing or information retrieving). If you want to apply ZEN2 to those tasks, you can use ZEN2 in the same way as other pre-trained language models (e.g., BERT), where you may want to add a task-specific decoder on the top of ZEN2.

We hope this information can help.

Best,
Yuanhe, Tian
Guimin, Chen
